name: Check and Update Blocklist

on:
  schedule:
    - cron: '30 2 * * *' # Runs every day at 2:30 AM
  workflow_dispatch:

jobs:
  update-blocklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run update script
        run: |
          chmod +x scripts/check_for_updates.sh
          ./scripts/check_for_updates.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}