name: Update Blocklist

on:
  repository_dispatch:
    types: [update_blocklist]     # Triggered by Pipedream custom event
  workflow_dispatch:              # Manual trigger from UI / API

permissions:
  contents: write                 # Minimal required to push changes

concurrency:
  group: update-blocklist
  cancel-in-progress: true        # Avoid overlapping runs

jobs:
  update-blocklist:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Keep depth=1 for speed (if script needs full history then set 0)
          fetch-depth: 1

      - name: Show dispatch payload (if repository_dispatch)
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          echo "Received repository_dispatch payload:"
          echo '${{ toJson(github.event.client_payload) }}' > payload.json
          jq '.' payload.json || cat payload.json

      # (jq comes preinstalled on ubuntu-latest runners; no install step required)

      - name: Run update script
        shell: bash
        run: |
          set -euo pipefail
          chmod +x scripts/update.sh
          ./scripts/update.sh

      - name: Summarize changed repos from payload (optional)
        if: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.changed_repos }}
        run: |
          echo "Changed repositories reported by upstream:"
          echo '${{ toJson(github.event.client_payload.changed_repos) }}' \
            | jq -r '.[] | "\(.owner)/\(.repo)@\(.branch) | new commits: \(.newCommitCount) | rewrite: \(.historyRewrite)"'

      - name: Commit and push changes (if any)
        shell: bash
        env:
          GIT_AUTHOR_NAME: cyber-bot
          GIT_AUTHOR_EMAIL: cyber-bot@users.noreply.github.com
          GIT_COMMITTER_NAME: cyber-bot
          GIT_COMMITTER_EMAIL: cyber-bot@users.noreply.github.com
        run: |
          set -euo pipefail
          # Stage & commit only when there are modifications
          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git add -A
          TS="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git config user.name  "${GIT_AUTHOR_NAME}"
          git config user.email "${GIT_AUTHOR_EMAIL}"
          git commit -m "Updated blocklist (${TS})"
          git push