name: Check and Update Blocklist

on:
  schedule:
    - cron: '30 2 * * *' # Runs every day at 2:30 AM
  workflow_dispatch:

jobs:
  update-blocklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run update script
        run: |
          chmod +x scripts/check_for_updates.sh
          ./scripts/check_for_updates.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Schedule random time for next run
        run: |
          chmod +x scripts/schedule_random_time.sh
          ./scripts/schedule_random_time.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "cyber-bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Cantue35/adobe-blocklist.git
          git add .
          git commit -m "Updated blocklist (scheduled update)"
          git push origin main